### ISSUE TITLE
missing requirements.txt file?

### ISSUE THREAD

**Issue by alhazmy13** [alialghamdi/whatsapp_analysis_bash#1]
Since you are using [emoji](https://pypi.org/project/emoji/) dependance, then it's better to include a `requirement.txt` file or update your remade file with `pip install emoji`
https://github.com/alialghamdi/whatsapp_analysis_bash/blob/7d2fd226ba5629a53c017bb392336aa3b29fa190/emoji.py#L7

However, I'm not sure why this line in your file? there's no any usage of it!

**Comment by alialghamdi** [comment]
Thanks for the requirement.txt tip, 

As for importing emoji, it must have been when I was testing something else.
